server:
  port: 8888

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Active la découverte automatique des routes via Eureka
          lower-case-service-id: true  # Utilise les noms en minuscules
    # Ajout des routes manuelles si nécessaire (exemple)
    routes:
      - id: authService
        uri: lb://AUTH-SERVICE
        predicates:
          - Path=/api/auth/**

      - id: apprenantService
        uri: lb://APPRENANT-SERVICE
        predicates:
          - Path=/api/rendus**

      - id: briefService
        uri: lb://BRIEF-SERVICE
        predicates:
          - Path=/Briefs/**

      - id: competenceService
        uri: lb://COMPETENCE-SERVICE
        predicates:
          - Path=/competences/**

      - id: ENAA-SKills
        uri: lb://VALIDATION-SERVICE
        predicates:
          - Path=/validations/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
