version: '3.8'

services:
  brief-mysql:
    image: mysql:8.0
    container_name: brief-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: briefdb
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - brief-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - brief-network

  brief-service:
    build: .
    container_name: brief-service
    depends_on:
      brief-mysql:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - brief-network



volumes:
  mysql-data:
  jenkins_home:

networks:
  brief-network:


