pipeline {
	agent any

   tools {
		maven 'Maven 3.9.10'
         jdk 'JDK 17'//configurer jdk
}

    stages {
		stage('Clone') {
			steps {
				git 'https://github.com/hajar-tech/enaaSkills_app_microservices.git'
            }
        }

        stage('Build') {
			steps {
				sh 'mvn clean install'
            }
        }

        stage('Tests') {
			steps {
				sh 'mvn test'
            }
        }
    }
}
